services:
  app:
    build: .

  db:
    build: db/.
    restart: always
    ports:
      - "33060:3306"

  world:
    build:
      context: ./db
      dockerfile: world.Dockerfile
    restart: always
    ports:
      - "33061:3306"