name: Test Population Report
on: push

jobs:
  build:
    name: Build and run population module
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Set up JDK 26
        uses: actions/setup-java@v5
        with:
          java-version: '26'
          distribution: 'adopt'

      - name: Build population module
        run: mvn -pl population -am package

      - name: Start world database
        run: docker compose up --build -d world

      - name: Run population reports
        run: java -jar population/target/*-jar-with-dependencies.jar
        env:
          DB_HOST: localhost
          DB_PORT: "33061"

      - name: Stop database
        if: always()
        run: docker compose down